<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>

    <ApplicationIcon>..\NzbDrone.Host\Mangarr.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="!$(RuntimeIdentifier.StartsWith('win'))">
    <AssemblyName>Mangarr</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Host\Mangarr.Host.csproj" />
    <ProjectReference Include="..\Mangarr.RuntimePatches\Mangarr.RuntimePatches.csproj" />
  </ItemGroup>
</Project>
