// This file is automatically generated.
// Please do not change this file!
//
// Phase 27.1 Plan 27.1-05 Task 6 — stub CSS module peer. The
// `ImportListSettings.tsx` component does not import this module; the file
// ships as a deliberate stub so future selectors can be added without
// re-authoring the typing peer. `Readonly<Record<string, string>>` matches
// the Plan 27.1-02 ImportListOptions.css.d.ts precedent.
declare const styles: Readonly<Record<string, string>>;
export default styles;
