// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chapterNumber': string;
  'language': string;
  'monitored': string;
  'scanlationGroup': string;
  'status': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
