// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'backdrop': string;
  'backdropOverlay': string;
  'contentContainer': string;
  'details': string;
  'detailsLabel': string;
  'header': string;
  'headerContent': string;
  'info': string;
  'innerContentBody': string;
  'links': string;
  'mangaProgressLabel': string;
  'monitorToggleButton': string;
  'overview': string;
  'path': string;
  'poster': string;
  'sizeOnDisk': string;
  'statusName': string;
  'tabBody': string;
  'tabButton': string;
  'tabButtonActive': string;
  'tabContainer': string;
  'tags': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
  'translationProfileName': string;
}
export const cssExports: CssExports;
export default cssExports;
