// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionRow': string;
  'chapterNumber': string;
  'chapterRow': string;
  'checkboxColumn': string;
  'empty': string;
  'releaseDate': string;
  'selectAllButton': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
