// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adultRow': string;
  'backdrop': string;
  'body': string;
  'chips': string;
  'closeButton': string;
  'drawer': string;
  'header': string;
  'overlay': string;
  'rangeInput': string;
  'rangeRow': string;
  'rangeSeparator': string;
  'section': string;
  'sectionLabel': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
