// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applyRow': string;
  'empty': string;
  'presetsRow': string;
  'saveRow': string;
  'sectionLabel': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
