// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'modeRow': string;
  'namePath': string;
  'segment': string;
  'segmentActive': string;
  'segmented': string;
  'seriesCount': string;
  'suggestion': string;
  'suggestionIcon': string;
  'suggestionMain': string;
  'suggestions': string;
}
export const cssExports: CssExports;
export default cssExports;
