// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chip': string;
  'exclude': string;
  'icon': string;
  'include': string;
  'label': string;
}
export const cssExports: CssExports;
export default cssExports;
