// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addMetadataSource': string;
  'center': string;
  'metadataSources': string;
}
export const cssExports: CssExports;
export default cssExports;
