// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enableAutomaticAdd': string;
  'implementation': string;
  'name': string;
  'rootFolderPath': string;
  'tags': string;
  'translationProfileId': string;
}
export const cssExports: CssExports;
export default cssExports;
