<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Mangarr.Api.V5</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="9.5.4" />
		<PackageReference Include="Ical.Net" Version="4.3.1" />
		<PackageReference Include="NLog" Version="5.5.1" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\NzbDrone.Core\Mangarr.Core.csproj" />
		<ProjectReference Include="..\Mangarr.Http\Mangarr.Http.csproj" />
	</ItemGroup>
</Project>
