// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'modalFooter': string;
  'searchInput': string;
  'searchInputContainer': string;
  'searchLabel': string;
  'searchLabelContainer': string;
  'summaryDetail': string;
}
export const cssExports: CssExports;
export default cssExports;
