// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customFormatProfile': string;
  'name': string;
  'nameContainer': string;
  'scoreRange': string;
}
export const cssExports: CssExports;
export default cssExports;
