// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addCustomFormatProfile': string;
  'center': string;
  'customFormatProfiles': string;
}
export const cssExports: CssExports;
export default cssExports;
