// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'emptyHeading': string;
  'emptyHelp': string;
  'filterInput': string;
  'mangaRow': string;
  'metadata': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
