// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteFilesMessage': string;
  'message': string;
  'modalFooter': string;
  'modalFooterButtons': string;
  'path': string;
  'pathContainer': string;
  'statistics': string;
}
export const cssExports: CssExports;
export default cssExports;
