// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hiddenDeleteHook': string;
  'languages': string;
  'name': string;
  'nameContainer': string;
  'translationProfile': string;
}
export const cssExports: CssExports;
export default cssExports;
