using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using FluentValidation.Results;
using Newtonsoft.Json;
using NLog;
using NzbDrone.Common.Http;
using NzbDrone.Core.Configuration;
using NzbDrone.Core.Indexers.Http;
using NzbDrone.Core.IndexerSearch.Definitions;
using NzbDrone.Core.Localization;
using NzbDrone.Core.Parser.Manga;
using NzbDrone.Core.Parser.Model;

namespace NzbDrone.Core.Indexers.Comix
{
    /// <summary>
    /// v1 reference port #1 — comix.to. Direct port from
    /// <c>keiyoushi/extensions-source/src/en/comix/Comix.kt</c> (Apache-2.0; PR #11658
    /// merged 2025-11-16; rebased against the live <c>/api/v1</c> shape on 2026-05-08
    /// during the comix-indexer-404 debug session).
    ///
    /// <para>
    /// Cloudflare posture: comix.to is Cloudflare-protected. UA override IS exposed via
    /// Settings UI (<see cref="ComixIndexerSettings.UserAgentOverride"/> has
    /// <c>[FieldDefinition]</c>) per RESEARCH.md anti-bot section — users may spoof a
    /// browser UA to dodge low-grade blocks. Persistent CF 403 → auto-disable via
    /// <see cref="IIndexerSourceStatusService"/> (D-17) + Health Check warning.
    /// </para>
    ///
    /// <para>
    /// Manga key resolution: comix.to keys manga by an opaque <c>hid</c>
    /// (e.g. <c>"mr3m0"</c>) — NOT a slug. The Manga model has no <c>ComixHash</c> field,
    /// so we resolve title → hid at search time by hitting
    /// <c>/api/v1/manga?keyword={title}</c> first and picking the top match. Future v2
    /// metadata-source linkage may persist the hid on the Manga model.
    /// </para>
    ///
    /// <para>
    /// Anti-bot token: <c>/api/v1/manga/{hid}/chapters</c> requires a <c>_=&lt;token&gt;</c>
    /// query parameter generated by <see cref="ComixHash.GenerateHash"/> (a 5-round RC4 +
    /// per-byte mutation transform of the URL path). Without it the endpoint returns 403
    /// <c>"Missing token."</c>. The token is path-keyed; URL-encoded into the request line.
    /// </para>
    ///
    /// <para>
    /// Single-source convention: comix.to does NOT expose scanlation-group metadata on
    /// every chapter (only when the chapter is community-translated, vs <c>isOfficial=1</c>);
    /// parser populates <c>ReleaseInfo.ScanlationGroup</c> from the row's <c>group.name</c>
    /// when present. comix.to is English-only; parser sets
    /// <c>ReleaseInfo.TranslatedLanguage = "en"</c>.
    /// </para>
    ///
    /// <para>
    /// Phase 4's in-process downloader will consume
    /// <c>ReleaseInfo.DownloadUrl = https://comix.to/api/v1/chapters/{chapterId}/pages</c>
    /// (chapter manifest URL — NOT a single image) and call
    /// <see cref="GetDownloadHeaders(ReleaseInfo)"/> (returns
    /// <c>{"Referer": "https://comix.to/"}</c>) per D-14 — keiyoushi pattern.
    /// </para>
    /// </summary>
    public class ComixIndexer : HttpAggregatorBase<ComixIndexerSettings>
    {
        public override string Name => "Comix";
        public override DownloadProtocol Protocol => DownloadProtocol.Http;
        public override string DefaultSourceKey => "comix.to";

        public ComixIndexer(
            IHttpClient httpClient,
            IIndexerStatusService indexerStatusService,
            IIndexerSourceStatusService sourceStatusService,
            IConfigService configService,
            IMangaParsingService parsingService,
            Logger logger,
            ILocalizationService localizationService)
            : base(httpClient, indexerStatusService, sourceStatusService, configService, parsingService, logger, localizationService)
        {
        }

        public override IIndexerRequestGenerator GetRequestGenerator()
            => new ComixRequestGenerator { Settings = Settings };

        public override IParseIndexerResponse GetParser()
            => new ComixParser { BaseUrl = Settings.BaseUrl };

        // ── Phase 3 D-01 — manga Fetch overloads ─────────────────────────────────────
        // HttpAggregatorBase narrows these to ABSTRACT (Plan 03-02 D-02), so we provide a
        // concrete implementation here. We resolve title → hid via the search endpoint
        // BEFORE delegating to FetchReleases (which builds the chapter-list URL signed with
        // the comix.to anti-bot token).
        public override async Task<IList<ReleaseInfo>> Fetch(MangaSearchCriteria searchCriteria)
        {
            if (!SupportsSearch)
            {
                return Array.Empty<ReleaseInfo>();
            }

            var hid = await ResolveMangaHashAsync(searchCriteria?.Manga?.Title, searchCriteria?.Manga?.CleanTitle);
            if (string.IsNullOrWhiteSpace(hid))
            {
                _logger.Debug("Comix: no manga hid resolved for '{0}' — skipping fetch.", searchCriteria?.Manga?.Title);
                return Array.Empty<ReleaseInfo>();
            }

            return await FetchReleases(g =>
            {
                if (g is ComixRequestGenerator crg)
                {
                    crg.ResolvedMangaHash = hid;
                    crg.ResolvedMangaSlug = hid; // bare hid is sufficient; slug-form is optional metadata
                }

                return g.GetSearchRequests(searchCriteria);
            });
        }

        public override async Task<IList<ReleaseInfo>> Fetch(ChapterSearchCriteria searchCriteria)
        {
            if (!SupportsSearch)
            {
                return Array.Empty<ReleaseInfo>();
            }

            var hid = await ResolveMangaHashAsync(searchCriteria?.Manga?.Title, searchCriteria?.Manga?.CleanTitle);
            if (string.IsNullOrWhiteSpace(hid))
            {
                _logger.Debug("Comix: no manga hid resolved for '{0}' — skipping fetch.", searchCriteria?.Manga?.Title);
                return Array.Empty<ReleaseInfo>();
            }

            return await FetchReleases(g =>
            {
                if (g is ComixRequestGenerator crg)
                {
                    crg.ResolvedMangaHash = hid;
                    crg.ResolvedMangaSlug = hid;
                }

                return g.GetSearchRequests(searchCriteria);
            });
        }

        /// <summary>
        /// Look up a manga title against comix.to's <c>/api/v1/manga?keyword=</c> search
        /// endpoint and return the top-match's <c>hid</c>. Returns null when:
        /// <list type="bullet">
        /// <item>the title is empty,</item>
        /// <item>the search call fails (network or parse error — logged at Debug),</item>
        /// <item>the search returned zero items.</item>
        /// </list>
        /// On null return, the caller should produce an empty release list — comix.to has no
        /// match for this manga and that is a normal state.
        /// </summary>
        private async Task<string> ResolveMangaHashAsync(string title, string cleanTitle)
        {
            // Prefer the full title for keyword search (cleanTitle drops punctuation that
            // can change comix.to's tokenizer behavior). Fall back to cleanTitle if title
            // is empty.
            var keyword = !string.IsNullOrWhiteSpace(title) ? title : cleanTitle;
            if (string.IsNullOrWhiteSpace(keyword))
            {
                return null;
            }

            try
            {
                var generator = (ComixRequestGenerator)GetRequestGenerator();
                var url = generator.BuildSearchUrl(keyword);
                var request = new HttpRequest(url, HttpAccept.Json);
                request.Headers["Referer"] = $"{Settings.BaseUrl.TrimEnd('/')}/";
                request.RateLimitKey = SourceKey;
                request.RateLimit = RateLimit;
                request.Headers["User-Agent"] = ResolveUserAgent();

                var response = await _httpClient.GetAsync(request);
                if (string.IsNullOrWhiteSpace(response?.Content))
                {
                    return null;
                }

                var envelope = JsonConvert.DeserializeObject<ComixMangaListResponse>(response.Content);
                if (envelope?.Result?.Items == null || envelope.Result.Items.Count == 0)
                {
                    return null;
                }

                // Match preference: exact (case-insensitive) title match if available, else
                // first hit. comix.to's keyword search occasionally returns near-misses
                // (sub-string hits) ahead of the exact title — guard against that.
                foreach (var item in envelope.Result.Items)
                {
                    if (item != null && !string.IsNullOrWhiteSpace(item.Hid)
                        && string.Equals(item.Title, keyword, StringComparison.OrdinalIgnoreCase))
                    {
                        return item.Hid;
                    }
                }

                return envelope.Result.Items[0]?.Hid;
            }
            catch (Exception ex)
            {
                _logger.Debug(ex, "Comix: title-to-hid resolution failed for '{0}'.", keyword);
                return null;
            }
        }

        // Sonarr divergence: Phase 15 Plan 15-10 cascade absorption — TV-shape Fetch overrides
        // (Single|Season|Daily|Anime|SpecialEpisodeSearchCriteria, etc.) stripped per Plan 15-10
        // IndexerSearch/Definitions DELETE. Manga overloads above are canonical.

        // ── Phase 3 D-14 — per-source HTTP headers for Phase 4 in-process downloader ───────
        // comix.to MANDATES Referer: https://comix.to/ on chapter requests per keiyoushi
        // headersBuilder() pattern. Phase 4's in-process downloader applies this to each
        // image GET via this hook.
        public override Dictionary<string, string> GetDownloadHeaders(ReleaseInfo release)
            => new Dictionary<string, string>
            {
                ["Referer"] = $"{Settings.BaseUrl.TrimEnd('/')}/"
            };

        // ── Phase 4 D-01 — Comix /api/v1/chapters/{id}/pages dereference ─────────────
        // Returns: { result: { images: [{url}, ...] } } — durable URLs (no token rotation).
        // ExpiresAt = null because comix.to URLs do not expire; the auto-re-fetch on 403/410
        // (D-03) is a never-fired safety net for this source.
        //
        // Referer header: handled by GetDownloadHeaders override (returns
        // "Referer: https://comix.to/"). Plan 04-03's ChapterPageFetcher applies that header
        // before each image GET via the GetDownloadHeaders hook.
        //
        // CRITICAL (Pitfall 1): RateLimitKey set EXPLICITLY at the call site to SourceKey so
        // the chapter-pages GET shares the per-SourceKey budget with indexer poll path.
        public override async Task<ChapterManifest> GetChapterPages(ReleaseInfo release)
        {
            var req = new HttpRequest(release.DownloadUrl);   // already https://comix.to/api/v1/chapters/{id}/pages
            req.RateLimitKey = SourceKey;                                          // Phase 1 D-11 — shared budget
            req.Headers["User-Agent"] = ResolveUserAgent();                        // Phase 1 D-13 — honest UA
            req.Headers["Referer"] = $"{Settings.BaseUrl.TrimEnd('/')}/";          // Phase 3 D-Comix Cloudflare Pitfall

            var resp = await _httpClient.GetAsync<ComixChapterPagesResponse>(req);
            var pageUrls = resp.Resource.Pages;
            var pages = new List<ChapterPage>(pageUrls.Count);
            for (var i = 0; i < pageUrls.Count; i++)
            {
                pages.Add(new ChapterPage
                {
                    Url = pageUrls[i],
                    PageIndex = i + 1,
                    ContentTypeHint = null
                });
            }

            return new ChapterManifest
            {
                Pages = pages,
                ScanlationGroup = release.ScanlationGroup,    // typically null for Comix; non-null for community translations
                TotalCount = pageUrls.Count,
                ExpiresAt = null                               // durable URLs
            };
        }

        protected override Task Test(List<ValidationFailure> failures)
        {
            // Lightweight Test() implementation — honors the abstract contract.
            // Real connectivity verification happens via the GH-Actions soak workflow
            // (Plan 03-06) + Wave 0 fixtures. Mirrors MangaDexIndexer posture.
            return Task.CompletedTask;
        }
    }
}
