// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'freeSpace': string;
  'label': string;
  'link': string;
  'pathContainer': string;
  'unmappedFolders': string;
}
export const cssExports: CssExports;
export default cssExports;
