// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'banner': string;
  'bannerGrow': string;
  'certification': string;
  'genres': string;
  'monitorNewItems': string;
  'path': string;
  'qualityProfileId': string;
  'ratings': string;
  'releaseGroups': string;
  'releaseTypes': string;
  'sizeOnDisk': string;
  'sortTitle': string;
  'status': string;
  'tags': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
