<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common.Test\Mangarr.Common.Test.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Mangarr.Test.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Windows\Mangarr.Windows.csproj" />
  </ItemGroup>
</Project>
