namespace NzbDrone.Core.DecisionEngine;

public enum DownloadRejectionReason
{
    Unknown,
    UnknownSeries,
    UnknownEpisode,
    MatchesAnotherSeries,
    UnableToParse,
    Error,
    DecisionError,
    MinimumAgeDelay,
    MinimumAgeDelayPushed,
    SeriesNotMonitored,
    EpisodeNotMonitored,
    HistoryRecentCutoffMet,
    HistoryCdhDisabledCutoffMet,
    HistoryHigherPreference,
    HistoryHigherRevision,
    HistoryCutoffMet,
    HistoryCustomFormatCutoffMet,
    HistoryCustomFormatScore,
    HistoryCustomFormatScoreIncrement,
    HistoryUpgradesNotAllowed,
    NoMatchingTag,
    PropersDisabled,
    ProperForOldFile,
    WrongEpisode,
    WrongSeason,
    WrongSeries,
    FullSeason,
    UnknownRuntime,
    BelowMinimumSize,
    AboveMaximumSize,
    AlreadyImportedSameHash,
    AlreadyImportedSameName,
    UnknownReleaseGroup,
    ReleaseGroupDoesNotMatch,
    IndexerDisabled,
    Blocklisted,
    CustomFormatMinimumScore,
    MinimumFreeSpace,
    FullSeasonNotAired,
    MaximumSizeExceeded,
    MinimumAge,
    MaximumAge,
    MultiSeason,
    Sample,
    ProtocolDisabled,
    QualityNotWanted,
    QualityUpgradesDisabled,
    QueueHigherPreference,
    QueueHigherRevision,
    QueueCutoffMet,
    QueueCustomFormatCutoffMet,
    QueueCustomFormatScore,
    QueueCustomFormatScoreIncrement,
    QueueUpgradesNotAllowed,
    QueuePropersDisabled,
    Raw,
    MustContainMissing,
    MustNotContainPresent,
    RepackDisabled,
    RepackUnknownReleaseGroup,
    RepackReleaseGroupDoesNotMatch,
    ExistingFileHasMoreEpisodes,
    AmbiguousNumbering,
    NotSeasonPack,
    SplitEpisode,
    MinimumSeeders,
    DiskHigherPreference,
    DiskHigherRevision,
    DiskCutoffMet,
    DiskCustomFormatCutoffMet,
    DiskCustomFormatScore,
    DiskCustomFormatScoreIncrement,
    DiskUpgradesNotAllowed,
    DiskNotUpgrade,
    BeforeAirDate,

    // Phase 5 D-06 — TPROFILE outer enforcer reject reason (LanguageInTranslationProfileSpecification).
    LanguageNotInProfile,

    // Phase 5 D-07 — CF inner enforcer upper-bound reject reason (CustomFormatMinimumScoreSpecification).
    // CustomFormatMinimumScore (lower-bound) already exists on this enum (Sonarr precedent).
    CustomFormatMaximumScore,

    // Phase 5 D-06 — manga core gate reject reasons (manga-side siblings to TV SeriesNotMonitored / EpisodeNotMonitored).
    MangaNotMonitored,
    ChapterMissingFromRelease,
    ChapterNotMonitored,
    ChapterNotRequested,
    ChapterAlreadyImported,
    ChapterAlreadyQueued,

    // Phase 5 D-06 — manga operational size gate reject reasons (siblings to TV BelowMinimumSize / MaximumSizeExceeded
    // but distinct names so the operational-vs-quality distinction stays clear in logs).
    SizeTooSmall,
    SizeTooLarge
}
