// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badges': string;
  'card': string;
  'excludeButton': string;
  'poster': string;
  'posterContainer': string;
  'posterPlaceholder': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
