// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyState': string;
  'filterButton': string;
  'grid': string;
  'toolbar': string;
  'toolbarLeft': string;
  'toolbarRight': string;
  'topInput': string;
  'topLabel': string;
  'undoButton': string;
  'undoText': string;
  'undoToast': string;
}
export const cssExports: CssExports;
export default cssExports;
