// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'badgeScore': string;
  'badgeStatus': string;
  'badgeType': string;
  'body': string;
  'card': string;
  'coverBadges': string;
  'coverScore': string;
  'excludeButton': string;
  'genreLine': string;
  'meta': string;
  'poster': string;
  'posterContainer': string;
  'posterPlaceholder': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
