// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyState': string;
  'scanContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
