// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customFormatProfile': string;
  'folder': string;
  'manga': string;
  'mangaName': string;
  'monitor': string;
  'selectCell': string;
  'translationProfile': string;
}
export const cssExports: CssExports;
export default cssExports;
